server:
  port: 8082
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Stores/nlp-engine/fuzzy/city,/nlp-engine/fuzzy/locality,/user/oauth/token,/user-otp/v1/_send,/otp/v1/_validate,/user/citizen/_create,/localization/messages,/localization/messages/v1/_search,/user/password/nologin/_update,/tenant/v1/tenant/_search,/egov-location/boundarys,/egov-location/boundarys/boundariesByBndryTypeNameAndHierarchyTypeName,/egov-location/boundarys/getLocationByLocationName,/egov-mdms-service/v1/_search,/egov-location/location/v11/geography/_search,/filestore/v1/files/url,/pt-calculator-v2/billing-slab/_search,/eus,/egov-searcher/property-services/propertyopensearch/_get,/egov-location/location/v11/boundarys/_search,/whatsapp-webhook/messages,/xstate-chatbot/message,/dashboard-ingest/ingest/upload,/edcr/rest/dcr/downloadfile,/xstate-chatbot/status,/xstate-chatbot/reminder,/egov-searcher/water-services/wateropensearch/_get,/egov-searcher/sewerage-services/sewerageopensearch/_get,/notification-sms/smsbounce/callback,/birth-death-services/birth/_viewcertdata,/inbox/v1/dss/_search
